FROM onsdigital/java-node-component

WORKDIR /usr/src

ADD web target/web
ADD *-jar-with-dependencies.jar target/

CMD java -Xmx2048m                                                 \
    -Drestolino.files="target/web"                                 \
    -Drestolino.packageprefix=com.github.onsdigital.ermintrude.api \
    -jar target/*-jar-with-dependencies.jar
