---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-dp-node-java

inputs:
  - name: ermintrude

outputs:
  - name: build

run:
  path: ermintrude/ci/scripts/build.sh
